//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canvas_ImageCategories
    {
        public int CanvasID { get; set; }
        public int ImageCategoryID { get; set; }
    
        public virtual ImageCategory ImageCategory { get; set; }
    }
}
