//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canvas
    {
        public int CanvasId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<bool> Shared { get; set; }
        public string ProjectType { get; set; }
        public string PreviewURL { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsShareable { get; set; }
        public Nullable<bool> CutMirror { get; set; }
        public Nullable<short> CutQty { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public Nullable<long> AccessCount { get; set; }
        public Nullable<System.Guid> UniqueID { get; set; }
        public string ExtendedAttributes { get; set; }
    }
}
