//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartridgeActivity
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CartridgeID { get; set; }
        public string CartridgeName { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string SKU { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
