//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public int ProfileID { get; set; }
        public int CommentStatusID { get; set; }
        public int CommentedProfileID { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual Comment Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual CommentStatu CommentStatu { get; set; }
        public virtual Profile Profile1 { get; set; }
    }
}
