//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CricutProjectEngineEntities : DbContext
    {
        public CricutProjectEngineEntities()
            : base("name=CricutProjectEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public virtual DbSet<ApplicationSettingType> ApplicationSettingTypes { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<CartridgeActivity> CartridgeActivities { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CommentStatu> CommentStatus { get; set; }
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<CrafterTag> CrafterTags { get; set; }
        public virtual DbSet<CraftInterestTag> CraftInterestTags { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<Follower> Followers { get; set; }
        public virtual DbSet<Frequency> Frequencies { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<InappropriateFlagReason> InappropriateFlagReasons { get; set; }
        public virtual DbSet<NotificationFrequency> NotificationFrequencies { get; set; }
        public virtual DbSet<NotificationHistory> NotificationHistories { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfileAward> ProfileAwards { get; set; }
        public virtual DbSet<ProfileContest> ProfileContests { get; set; }
        public virtual DbSet<ProfileNotification> ProfileNotifications { get; set; }
        public virtual DbSet<ProfilePhoto> ProfilePhotoes { get; set; }
        public virtual DbSet<ProfileStatu> ProfileStatus { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectAward> ProjectAwards { get; set; }
        public virtual DbSet<ProjectAward1> ProjectAwards1 { get; set; }
        public virtual DbSet<ProjectCartridge> ProjectCartridges { get; set; }
        public virtual DbSet<ProjectComment> ProjectComments { get; set; }
        public virtual DbSet<ProjectCutFile> ProjectCutFiles { get; set; }
        public virtual DbSet<ProjectDifficulty> ProjectDifficulties { get; set; }
        public virtual DbSet<ProjectFollower> ProjectFollowers { get; set; }
        public virtual DbSet<ProjectImage> ProjectImages { get; set; }
        public virtual DbSet<ProjectProduct> ProjectProducts { get; set; }
        public virtual DbSet<ProjectRating> ProjectRatings { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<ProjectStep> ProjectSteps { get; set; }
        public virtual DbSet<ProjectStepImage> ProjectStepImages { get; set; }
        public virtual DbSet<ProjectTag> ProjectTags { get; set; }
        public virtual DbSet<ProjectTagGroup> ProjectTagGroups { get; set; }
        public virtual DbSet<ProjectTagNavigation> ProjectTagNavigations { get; set; }
        public virtual DbSet<ProjectTime> ProjectTimes { get; set; }
        public virtual DbSet<PromoSection> PromoSections { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<SocialConnection> SocialConnections { get; set; }
        public virtual DbSet<UserSelectedCartridge> UserSelectedCartridges { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<ViewedProject> ViewedProjects { get; set; }
    }
}
