//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageCategory()
        {
            this.Canvas_ImageCategories = new HashSet<Canvas_ImageCategories>();
            this.ImageCategories1 = new HashSet<ImageCategory>();
        }
    
        public int ImageCategoryID { get; set; }
        public string CategoryName { get; set; }
        public bool IsCategoryType { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<bool> IsProjectCategory { get; set; }
        public System.Guid UniqueID { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int ImageCategoryTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canvas_ImageCategories> Canvas_ImageCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageCategory> ImageCategories1 { get; set; }
        public virtual ImageCategory ImageCategory1 { get; set; }
    }
}
