//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class InappropriateFlagReason
    {
        public int ID { get; set; }
        public string Reason { get; set; }
        public int FlagSourceID { get; set; }
        public int FlagType { get; set; }
        public System.DateTime FlagDate { get; set; }
        public int ProfileID { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
