//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationHistory
    {
        public int ID { get; set; }
        public int ProfileNotificationId { get; set; }
        public System.DateTime SentDate { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
    
        public virtual ProfileNotification ProfileNotification { get; set; }
    }
}
