//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileNotification()
        {
            this.NotificationHistories = new HashSet<NotificationHistory>();
        }
    
        public int ID { get; set; }
        public int ProfileID { get; set; }
        public int NotificationTypeID { get; set; }
        public int NotificationFrequencyID { get; set; }
        public System.DateTime DateIn { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    
        public virtual NotificationFrequency NotificationFrequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationHistory> NotificationHistories { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
