//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.CartridgeActivities = new HashSet<CartridgeActivity>();
            this.Comments = new HashSet<Comment>();
            this.Comments1 = new HashSet<Comment>();
            this.Followers = new HashSet<Follower>();
            this.Followers1 = new HashSet<Follower>();
            this.InappropriateFlagReasons = new HashSet<InappropriateFlagReason>();
            this.ProfileAwards = new HashSet<ProfileAward>();
            this.ProfileContests = new HashSet<ProfileContest>();
            this.ProfileNotifications = new HashSet<ProfileNotification>();
            this.ProfilePhotoes = new HashSet<ProfilePhoto>();
            this.Projects = new HashSet<Project>();
            this.ProjectComments = new HashSet<ProjectComment>();
            this.ProjectFollowers = new HashSet<ProjectFollower>();
            this.ProjectRatings = new HashSet<ProjectRating>();
            this.SocialConnections = new HashSet<SocialConnection>();
            this.ViewedProjects = new HashSet<ViewedProject>();
            this.Badges = new HashSet<Badge>();
            this.CrafterTags = new HashSet<CrafterTag>();
            this.CraftInterestTags = new HashSet<CraftInterestTag>();
        }
    
        public int ID { get; set; }
        public string ScreenName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EmailVerification { get; set; }
        public Nullable<int> ProfileStatusID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Url { get; set; }
        public Nullable<short> Age { get; set; }
        public string Location { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string WebsiteName { get; set; }
        public string WebsiteURL { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> UpdatesFrequencyID { get; set; }
        public Nullable<int> FollowingFrequencyID { get; set; }
        public string FacebookID { get; set; }
        public string TwitterID { get; set; }
        public string GooglePlusID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> ShowGender { get; set; }
        public Nullable<bool> ShowAge { get; set; }
        public Nullable<bool> ShowLocation { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> LastProfileUpdate { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public bool IsScreenNameSet { get; set; }
        public Nullable<bool> ShowCricutProducts { get; set; }
        public string ForumName { get; set; }
        public bool IsProfileUpdated { get; set; }
        public bool Featured { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartridgeActivity> CartridgeActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follower> Followers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follower> Followers1 { get; set; }
        public virtual Frequency Frequency { get; set; }
        public virtual Frequency Frequency1 { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InappropriateFlagReason> InappropriateFlagReasons { get; set; }
        public virtual ProfileStatu ProfileStatu { get; set; }
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileAward> ProfileAwards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileContest> ProfileContests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileNotification> ProfileNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilePhoto> ProfilePhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectComment> ProjectComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFollower> ProjectFollowers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectRating> ProjectRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialConnection> SocialConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewedProject> ViewedProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Badge> Badges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrafterTag> CrafterTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CraftInterestTag> CraftInterestTags { get; set; }
    }
}
