//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTag()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ID { get; set; }
        public string TagName { get; set; }
        public int ProjectTagGroupID { get; set; }
        public bool IsUserDefined { get; set; }
        public Nullable<int> ProjectTagNavigationID { get; set; }
        public bool Display { get; set; }
        public string NavigationHTML { get; set; }
    
        public virtual ProjectTagGroup ProjectTagGroup { get; set; }
        public virtual ProjectTagNavigation ProjectTagNavigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}
