//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStepImage
    {
        public int ID { get; set; }
        public int ProjectStepID { get; set; }
        public int ProjectImageID { get; set; }
    
        public virtual ProjectImage ProjectImage { get; set; }
        public virtual ProjectStep ProjectStep { get; set; }
    }
}
