//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAward1
    {
        public int ProjectID { get; set; }
        public int AwardID { get; set; }
        public System.DateTime DateAwarded { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectAward ProjectAward { get; set; }
    }
}
