//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectImage()
        {
            this.Projects = new HashSet<Project>();
            this.ProjectStepImages = new HashSet<ProjectStepImage>();
        }
    
        public int ID { get; set; }
        public string ImageURL { get; set; }
        public bool IsVideo { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string MimeType { get; set; }
        public string Caption { get; set; }
        public int ImageOrder { get; set; }
        public int ProjectID { get; set; }
        public string YouTubeId { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStepImage> ProjectStepImages { get; set; }
    }
}
