//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCutFile
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string CutFileUrl { get; set; }
        public string MimeType { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string CutFileName { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
