//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectAwards = new HashSet<ProjectAward1>();
            this.ProjectCartridges = new HashSet<ProjectCartridge>();
            this.ProjectComments = new HashSet<ProjectComment>();
            this.ProjectCutFiles = new HashSet<ProjectCutFile>();
            this.ProjectFollowers = new HashSet<ProjectFollower>();
            this.ProjectImages = new HashSet<ProjectImage>();
            this.ProjectProducts = new HashSet<ProjectProduct>();
            this.ProjectRatings = new HashSet<ProjectRating>();
            this.ProjectSteps = new HashSet<ProjectStep>();
            this.ViewedProjects = new HashSet<ViewedProject>();
            this.ProjectTags = new HashSet<ProjectTag>();
            this.Contests = new HashSet<Contest>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int ProfileID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int StatusID { get; set; }
        public string ProjectURL { get; set; }
        public string OverviewDescription { get; set; }
        public Nullable<int> DifficultyID { get; set; }
        public Nullable<int> TimeRequiredID { get; set; }
        public string OtherMaterials { get; set; }
        public string Keywords { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<int> DefaultImageId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> KeplerCanvasID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> KeplerPublishDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ProjectDifficulty ProjectDifficulty { get; set; }
        public virtual ProjectImage ProjectImage { get; set; }
        public virtual ProjectTime ProjectTime { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAward1> ProjectAwards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCartridge> ProjectCartridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectComment> ProjectComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCutFile> ProjectCutFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFollower> ProjectFollowers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectImage> ProjectImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectRating> ProjectRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStep> ProjectSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewedProject> ViewedProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTag> ProjectTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contest> Contests { get; set; }
    }
}
