//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int ID { get; set; }
        public string ImageName { get; set; }
        public string RedirectURL { get; set; }
        public string Title { get; set; }
        public string AlternativeText { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int PromoSectionID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual PromoSection PromoSection { get; set; }
    }
}
