//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialConnection
    {
        public int ID { get; set; }
        public int ProfileID { get; set; }
        public string FBToken { get; set; }
        public Nullable<System.DateTime> FBTokenDate { get; set; }
        public Nullable<bool> FBShareNewlyPublished { get; set; }
        public Nullable<bool> FBShareDesignersFavorite { get; set; }
        public Nullable<bool> FBShareMyNewAwards { get; set; }
        public string TwitterToken { get; set; }
        public string TwitterSecret { get; set; }
        public Nullable<System.DateTime> TwitterTokenDate { get; set; }
        public Nullable<bool> TwitterShareNewlyPublished { get; set; }
        public Nullable<bool> TwitterShareDesignersFavorite { get; set; }
        public Nullable<bool> TwitterShareMyNewAwards { get; set; }
        public string FlickrToken { get; set; }
        public string FlickrUserId { get; set; }
        public Nullable<System.DateTime> FlickrTokenDate { get; set; }
        public string GoogleToken { get; set; }
        public Nullable<System.DateTime> GoogleTokenDate { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
