//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool LoggedIn { get; set; }
        public string IP { get; set; }
        public byte[] UKey { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public int CricutId { get; set; }
        public byte[] HMAC { get; set; }
        public bool HasPreviousLogin { get; set; }
        public double LastLatitude { get; set; }
        public double LastLongitude { get; set; }
        public byte[] CuttingKey { get; set; }
        public string SoftAuthorization { get; set; }
        public string CurrentMAC { get; set; }
        public string SoftE0 { get; set; }
        public string SoftE1 { get; set; }
        public byte[] SoftBlob { get; set; }
        public string CurrentE0 { get; set; }
        public string CurrentE1 { get; set; }
        public bool IsTester { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsCompany { get; set; }
    }
}
