//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Seed
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSelectedCartridge
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public int CartridgeID { get; set; }
        public int ProfileID { get; set; }
        public bool IsMachine { get; set; }
    }
}
